apiVersion: dipterv.my.domain/v1beta1
kind: Servicegraph
metadata:
  name: servicegraph
  namespace: default
spec:
  nodes:
    - name: front-end
      replicas: 2
      port: 80
      nodePort: 30000
      hpa:
        utilization: 10
        min_replicas: 2
        max_replicas: 5
      resources:
        memory: 100
        cpu: 100
      endpoints:
        - path: /instant
          cpuLoad: 10
          delay: 1
        - path: /chain
          cpuLoad: 20
          delay: 2
          callouts:
            - url: back-end:80/profile
            # - url: db:36/set
        - path: /iterate
          cpuLoad: 30
          delay: 3
          callouts:
            - url: back-end:80/profile
            - url: db:36/get
            - url: db:36/set
    - name: back-end
      replicas: 3
      port: 80
      resources:
        memory: 200
        cpu: 200
      endpoints:
        - path: /profile
          cpuLoad: 10
          delay: 1
          callouts:
            - url: db:36/get
        - path: /create
          cpuLoad: 20
          delay: 2
          callouts:
            - url: db:36/set
    - name: db
      replicas: 1
      port: 36
      resources:
        memory: 300
        cpu: 300
      endpoints:
        - path: /get
          cpuLoad: 10
          delay: 1
        - path: /set
          cpuLoad: 20
          delay: 2


